name: Ejecutar carga automática Reembolsos

on:
  schedule:
    - cron: '26 24 * * *'  # Todos los días a las 6:00 UTC
  workflow_dispatch:     # Para ejecución manual desde "Actions"

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl sqlalchemy psycopg2-binary requests

      - name: Ejecutar script Python
        env:
          PG_USER: ${{ secrets.PG_USER }}
          PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
          PG_HOST: ${{ secrets.PG_HOST }}
          PG_PORT: ${{ secrets.PG_PORT }}
          PG_DATABASE: ${{ secrets.PG_DATABASE }}
        run: python carga_reembolsos.py
